import ManuscriptPopulationConstruction
import ManuscriptExactGate
import ManuscriptJointClass
import ManuscriptGeneralLift
import ManuscriptLiftHessian
import ManuscriptLiftOracle
import ManuscriptPaperStatements

open NCSCPureStochasticLB.PaperExact

-- Revision 18: oracle-uniform kernel-family representation and top-level lower bounds.
#print axioms KernelModel.Family
#print axioms KernelModel.transcript_standardBorel
#print axioms KernelModel.historyModel
#print axioms KernelModel.Family.compile
#print axioms KernelModel.executionLaw
#print axioms KernelModel.compile_completeCode
#print axioms KernelModel.compile_law
#print axioms KernelModel.Legal
#print axioms KernelModel.legal_iff_compile
#print axioms KernelModel.codeLoss
#print axioms KernelModel.codeLoss_measurable
#print axioms KernelModel.risk
#print axioms KernelModel.compile_risk
#print axioms KernelModel.Family.representative
#print axioms KernelModel.representative_legal
#print axioms KernelModel.representative_pathwise
#print axioms KernelModel.representative_law
#print axioms KernelModel.representative_risk
#print axioms KernelModel.exists_uniform_representative
#print axioms KernelModel.BudgetAlgorithm
#print axioms KernelModel.complexity
#print axioms KernelModel.measured_complexity_le
#print axioms KernelModel.bv_complexity_lower
#print axioms KernelModel.as_complexity_lower

-- Revision 17: arbitrary-seed operational progress and primal risk bounds.
#print axioms GeneralProgress.eventCount
#print axioms GeneralProgress.eventCount_measurable
#print axioms GeneralProgress.eval_event_measure
#print axioms GeneralProgress.eventCount_integral
#print axioms GeneralProgress.eventCount_bad_le
#print axioms GeneralProgress.eventCount_good_ge
#print axioms GeneralProgress.revealEvent
#print axioms GeneralProgress.revealEvent_measurable
#print axioms GeneralProgress.revealEvent_measure_le
#print axioms GeneralProgress.commonEvent_step
#print axioms GeneralProgress.eventTape
#print axioms GeneralProgress.eventTape_count
#print axioms GeneralProgress.response_progress
#print axioms GeneralProgress.output_progress
#print axioms GeneralProgress.liftedOracle
#print axioms GeneralProgress.lifted_commonEvent_step
#print axioms GeneralProgress.seed_steps_ae
#print axioms GeneralProgress.trace_progress_probability
#print axioms GeneralProgress.lifted_progress_probability
#print axioms GeneralProgress.native_response_consistent
#print axioms GeneralProgress.native_progress_probability
#print axioms GeneralProgress.liftedRectOracle
#print axioms GeneralProgress.native_lifted_progress_probability
#print axioms GeneralProgress.probability_real_bound
#print axioms GeneralProgress.native_lifted_progress_real
#print axioms GeneralProgress.event_risk_lower
#print axioms GeneralProgress.trace_risk_lower
#print axioms GeneralProgress.native_lifted_risk_lower
#print axioms GeneralProgress.native_primal_moments

-- Revision 16: full guard preservation and a.e. finite-budget complexity equality.
#print axioms Rectangular.CausalGuard.ofActions_run_stop
#print axioms Rectangular.CausalGuard.ofActions_run_continue
#print axioms Rectangular.CausalGuard.guardedPolicy_preserves_relative
#print axioms Rectangular.CausalGuard.guardedPolicy_preserves
#print axioms Rectangular.CausalGuard.completeCode
#print axioms Rectangular.CausalGuard.completeCode_measurable
#print axioms Rectangular.CausalGuard.guardedPolicy_ae_run
#print axioms Rectangular.CausalGuard.guardedPolicy_ae_code
#print axioms Rectangular.CausalGuard.guardedPolicy_law
#print axioms Rectangular.CausalGuard.guardedPolicy_event
#print axioms Rectangular.CausalGuard.guardedPolicy_risk
#print axioms Rectangular.CausalGuard.stopAction_measurable
#print axioms Rectangular.CausalGuard.queryAction_rule_measurable
#print axioms Rectangular.CausalGuard.policyAction
#print axioms Rectangular.CausalGuard.policyAction_measurable
#print axioms Rectangular.CausalGuard.policyAction_stop
#print axioms Rectangular.CausalGuard.policyAction_continue
#print axioms Rectangular.CausalGuard.totalizedPolicy
#print axioms Rectangular.CausalGuard.totalizedPolicy_preserves
#print axioms Rectangular.CausalGuard.repairPolicy
#print axioms Rectangular.CausalGuard.repairPolicy_legal
#print axioms Rectangular.CausalGuard.repairPolicy_preserves
#print axioms Rectangular.CausalGuard.repairPolicy_ae_run
#print axioms Rectangular.CausalGuard.repairPolicy_ae_code
#print axioms Rectangular.CausalGuard.repairPolicy_law
#print axioms Rectangular.CausalGuard.repairPolicy_risk
#print axioms Rectangular.CausalGuard.AEFamilyLegal
#print axioms Rectangular.CausalGuard.repairFamily
#print axioms Rectangular.CausalGuard.repairFamily_legal
#print axioms Rectangular.CausalGuard.legal_implies_ae
#print axioms Rectangular.CausalGuard.repairFamily_risk
#print axioms Rectangular.CausalGuard.exists_pathwise_representative
#print axioms Rectangular.CausalGuard.ae_feasible_iff
#print axioms Rectangular.CausalGuard.aeComplexity
#print axioms Rectangular.CausalGuard.aeComplexity_eq

-- Revision 15: measurable causal guard and pathwise legality.
#print axioms Rectangular.CausalGuard.Seen
#print axioms Rectangular.CausalGuard.spent
#print axioms Rectangular.CausalGuard.seen_measurable
#print axioms Rectangular.CausalGuard.batchSize_decode_measurable
#print axioms Rectangular.CausalGuard.spent_measurable
#print axioms Rectangular.CausalGuard.Supported
#print axioms Rectangular.CausalGuard.supported_measurable
#print axioms Rectangular.CausalGuard.Allowed
#print axioms Rectangular.CausalGuard.allowed_measurable
#print axioms Rectangular.CausalGuard.zero_allowed
#print axioms Rectangular.CausalGuard.guard
#print axioms Rectangular.CausalGuard.guard_measurable
#print axioms Rectangular.CausalGuard.guard_allowed
#print axioms Rectangular.CausalGuard.guard_preserves
#print axioms Rectangular.CausalGuard.guard_idempotent
#print axioms Rectangular.CausalGuard.guard_horizon
#print axioms Rectangular.CausalGuard.guard_continue
#print axioms Rectangular.CausalGuard.guard_output
#print axioms Rectangular.CausalGuard.spent_append
#print axioms Rectangular.CausalGuard.spent_initial
#print axioms Rectangular.CausalGuard.seen_append
#print axioms Rectangular.CausalGuard.Relative
#print axioms Rectangular.CausalGuard.relative_initial
#print axioms Rectangular.CausalGuard.relative_halt
#print axioms Rectangular.CausalGuard.relative_prepend
#print axioms Rectangular.CausalGuard.ofActions
#print axioms Rectangular.CausalGuard.guardedPolicy
#print axioms Rectangular.CausalGuard.guardedPolicy_terminates
#print axioms Rectangular.CausalGuard.guardedPolicy_budget
#print axioms Rectangular.CausalGuard.guardedPolicy_initial_budget
#print axioms Rectangular.CausalGuard.guardedPolicy_support
#print axioms Rectangular.CausalGuard.guardedPolicy_legal

-- Revision 14: measurable legality, a.e. transfer and positive-mass paths.
#print axioms Rectangular.StochasticMemory.decodeTrace
#print axioms Rectangular.StochasticMemory.decodeTrace_code
#print axioms Rectangular.StochasticMemory.decodeTrace_code_measurable
#print axioms Rectangular.StochasticMemory.decodeTrace_measurable
#print axioms Rectangular.StochasticMemory.LegalCode
#print axioms Rectangular.StochasticMemory.legalCode_measurable
#print axioms Rectangular.StochasticMemory.legalCode_partial_iff
#print axioms Rectangular.StochasticMemory.native_legalCode_iff
#print axioms Rectangular.StochasticMemory.native_legalCode_iff_policy
#print axioms Rectangular.StochasticMemory.native_memory_kernel_ae
#print axioms Rectangular.StochasticMemory.native_memory_ae_legal_iff
#print axioms Rectangular.StochasticMemory.native_memory_ae_legal_iterated
#print axioms Rectangular.StochasticMemory.native_memory_ae_positive_paths
#print axioms Rectangular.StochasticMemory.native_memory_ae_all_paths
#print axioms Rectangular.StochasticMemory.bernoulli_path_atom
#print axioms Rectangular.StochasticMemory.native_memory_bernoulli_all_paths
#print axioms Rectangular.StochasticMemory.native_memory_bernoulli_one

-- Revision 13: complete native private-memory trace/law bridge.
#print axioms Rectangular.StochasticMemory.scriptStep
#print axioms Rectangular.StochasticMemory.scriptWorkspace
#print axioms Rectangular.StochasticMemory.scriptExecute
#print axioms Rectangular.StochasticMemory.script_before
#print axioms Rectangular.StochasticMemory.script_stopped
#print axioms Rectangular.StochasticMemory.script_result_stopped
#print axioms Rectangular.StochasticMemory.script_native
#print axioms Rectangular.StochasticMemory.script_succ_last
#print axioms Rectangular.StochasticMemory.script_step_view
#print axioms Rectangular.StochasticMemory.privatePath
#print axioms Rectangular.StochasticMemory.actionScript
#print axioms Rectangular.StochasticMemory.script_eq_memory
#print axioms Rectangular.StochasticMemory.separatedRun_succ
#print axioms Rectangular.StochasticMemory.separatedRun_script
#print axioms Rectangular.StochasticMemory.forward_memory_eq_native
#print axioms Rectangular.StochasticMemory.forward_memory_eq_native_finite
#print axioms Rectangular.StochasticMemory.native_memory_kernel_law
#print axioms Rectangular.StochasticMemory.native_memory_kernel_event
#print axioms Rectangular.StochasticMemory.native_memory_kernel_risk

-- Revision 12: separate internal/oracle coordinates and initialized joint laws.
#print axioms IndexedKernelRun.prod_unassoc_law
#print axioms IndexedKernelRun.prod_middle_swap_law
#print axioms IndexedKernelRun.attachInitial
#print axioms IndexedKernelRun.attachInitial_measurable
#print axioms IndexedKernelRun.attachInitial_law
#print axioms IndexedKernelRun.initialPack
#print axioms IndexedKernelRun.initialPack_measurable
#print axioms IndexedKernelRun.initialPack_law
#print axioms Rectangular.StochasticMemory.internal_oracle_vector_law
#print axioms Rectangular.StochasticMemory.roundVector
#print axioms Rectangular.StochasticMemory.roundVector_measurable
#print axioms Rectangular.StochasticMemory.roundVector_law
#print axioms Rectangular.StochasticMemory.separatedPack
#print axioms Rectangular.StochasticMemory.separatedPack_measurable
#print axioms Rectangular.StochasticMemory.separatedPack_law
#print axioms Rectangular.StochasticMemory.separatedRun
#print axioms Rectangular.StochasticMemory.separatedRun_measurable
#print axioms Rectangular.StochasticMemory.separated_joint_execution_law
#print axioms Rectangular.StochasticMemory.separated_joint_execution_event
#print axioms Rectangular.StochasticMemory.separated_joint_execution_risk
#print axioms Rectangular.StochasticMemory.projected_joint_execution_law
#print axioms Rectangular.StochasticMemory.nativeCompleteCode
#print axioms Rectangular.StochasticMemory.nativeCompleteCode_measurable
#print axioms Rectangular.StochasticMemory.native_dummy_seed_law

-- Revision 11: random initialization and full stopped history/private-memory laws.
#print axioms IndexedKernelRun.sequential_sample_law
#print axioms IndexedKernelRun.retained_sample_law
#print axioms IndexedKernelRun.InitialTape
#print axioms IndexedKernelRun.initialTapeMeasurableSpace
#print axioms IndexedKernelRun.initialTapeLaw
#print axioms IndexedKernelRun.initialTapeLaw_probability
#print axioms IndexedKernelRun.initializedRun
#print axioms IndexedKernelRun.initializedRun_measurable
#print axioms IndexedKernelRun.initializedLaw
#print axioms IndexedKernelRun.initializedRun_law
#print axioms Rectangular.StochasticMemory.JointState
#print axioms Rectangular.StochasticMemory.RoundContext
#print axioms Rectangular.StochasticMemory.contextInput
#print axioms Rectangular.StochasticMemory.contextInput_measurable
#print axioms Rectangular.StochasticMemory.preKernel
#print axioms Rectangular.StochasticMemory.preSample
#print axioms Rectangular.StochasticMemory.preSample_measurable
#print axioms Rectangular.StochasticMemory.preSample_law
#print axioms Rectangular.StochasticMemory.finishState
#print axioms Rectangular.StochasticMemory.finishState_measurable
#print axioms Rectangular.StochasticMemory.finishKernel
#print axioms Rectangular.StochasticMemory.finishSample
#print axioms Rectangular.StochasticMemory.finishSample_measurable
#print axioms Rectangular.StochasticMemory.finishSample_law
#print axioms Rectangular.StochasticMemory.jointKernel
#print axioms Rectangular.StochasticMemory.jointSample
#print axioms Rectangular.StochasticMemory.jointSample_measurable
#print axioms Rectangular.StochasticMemory.jointSample_law
#print axioms Rectangular.StochasticMemory.jointKernel_markov
#print axioms Rectangular.StochasticMemory.jointInitial
#print axioms Rectangular.StochasticMemory.jointInitial_measurable
#print axioms Rectangular.StochasticMemory.jointInitial_law
#print axioms Rectangular.StochasticMemory.joint_execution_law
#print axioms Rectangular.StochasticMemory.joint_execution_event
#print axioms Rectangular.StochasticMemory.joint_execution_risk
#print axioms Rectangular.StochasticMemory.jointSample_stop
#print axioms Rectangular.StochasticMemory.jointSample_stopped
#print axioms Rectangular.StochasticMemory.jointSample_continue

-- Revision 9: complete pointwise native trace and kernel-law bridge.
#print axioms Rectangular.KernelPolicy.TraceWorkspace
#print axioms Rectangular.KernelPolicy.workspaceView
#print axioms Rectangular.KernelPolicy.workspaceStep
#print axioms Rectangular.KernelPolicy.workspaceRun
#print axioms Rectangular.KernelPolicy.workspaceStep_before
#print axioms Rectangular.KernelPolicy.workspaceRun_before
#print axioms Rectangular.KernelPolicy.workspaceRun_stopped
#print axioms Rectangular.KernelPolicy.workspaceResult
#print axioms Rectangular.KernelPolicy.workspaceResult_prepend
#print axioms Rectangular.KernelPolicy.workspaceResult_stopped
#print axioms Rectangular.KernelPolicy.workspaceView_update
#print axioms Rectangular.KernelPolicy.prepend_empty_halt
#print axioms Rectangular.KernelPolicy.workspaceRun_native
#print axioms Rectangular.KernelPolicy.workspaceRun_succ_last
#print axioms Rectangular.KernelPolicy.workspaceStep_view
#print axioms Rectangular.KernelPolicy.workspaceRun_forward
#print axioms Rectangular.KernelPolicy.initialWorkspace
#print axioms Rectangular.KernelPolicy.initialExecutionState
#print axioms Rectangular.KernelPolicy.forwardResult
#print axioms Rectangular.KernelPolicy.workspaceResult_forward
#print axioms Rectangular.KernelPolicy.forwardResult_eq_native
#print axioms Rectangular.KernelPolicy.forwardResult_eq_native_finite
#print axioms Rectangular.KernelPolicy.forwardCompleteCode
#print axioms Rectangular.KernelPolicy.forwardCompleteCode_measurable
#print axioms Rectangular.KernelPolicy.forwardState_measurable
#print axioms Rectangular.KernelPolicy.native_kernel_execution_law
#print axioms Rectangular.KernelPolicy.native_kernel_execution_event
#print axioms Rectangular.KernelPolicy.native_kernel_execution_risk

-- Revision 8: exact product-coordinate and unused-final-seed bridges.
#print axioms IndexedKernelRun.pack
#print axioms IndexedKernelRun.pack_measurable
#print axioms IndexedKernelRun.finite_split_law
#print axioms IndexedKernelRun.pack_law
#print axioms IndexedKernelRun.drop_last_law
#print axioms IndexedKernelRun.paired_vector_law
#print axioms IndexedKernelRun.paired_pack_law
#print axioms Rectangular.KernelPolicy.rangeFinEquiv
#print axioms Rectangular.KernelPolicy.internalTapeLaw_prefix
#print axioms Rectangular.KernelPolicy.internal_oracle_pack_law
#print axioms Rectangular.KernelPolicy.separated_execution_law
#print axioms Rectangular.KernelPolicy.native_execution_dummy_seed_law
#print axioms Rectangular.KernelPolicy.separated_execution_risk

-- Revision 7: independent original-kernel composition and absorbing history laws.
#print axioms IndexedKernelRun.Tape
#print axioms IndexedKernelRun.tapeMeasurableSpace
#print axioms IndexedKernelRun.tapeLaw
#print axioms IndexedKernelRun.tapeLaw_probability
#print axioms IndexedKernelRun.run
#print axioms IndexedKernelRun.run_measurable
#print axioms IndexedKernelRun.law
#print axioms IndexedKernelRun.independent_step
#print axioms IndexedKernelRun.run_law
#print axioms Rectangular.KernelPolicy.ExecutionState
#print axioms Rectangular.KernelPolicy.advanceState
#print axioms Rectangular.KernelPolicy.advanceState_measurable
#print axioms Rectangular.KernelPolicy.executionKernel
#print axioms Rectangular.KernelPolicy.executionKernel_markov
#print axioms Rectangular.KernelPolicy.sampledStep
#print axioms Rectangular.KernelPolicy.sampledStep_measurable
#print axioms Rectangular.KernelPolicy.sampledStep_law
#print axioms Rectangular.KernelPolicy.sampled_execution_law
#print axioms Rectangular.KernelPolicy.advanceState_stopped
#print axioms Rectangular.KernelPolicy.executionKernel_stopped
#print axioms Rectangular.KernelPolicy.sampledStep_stop
#print axioms Rectangular.KernelPolicy.sampledStep_continue
#print axioms Rectangular.KernelPolicy.sampled_execution_event
#print axioms Rectangular.KernelPolicy.sampled_execution_risk

-- Revision 6: exact native execution and finite-window laws.
#print axioms Rectangular.KernelPolicy.execute
#print axioms Rectangular.KernelPolicy.execute_eq_run
#print axioms Rectangular.KernelPolicy.execute_prefix_congr
#print axioms Rectangular.KernelPolicy.run_prefix_congr
#print axioms Rectangular.KernelPolicy.completeCode
#print axioms Rectangular.KernelPolicy.completeCode_measurable
#print axioms Rectangular.KernelPolicy.decisionWindow
#print axioms Rectangular.KernelPolicy.extendWindow
#print axioms Rectangular.KernelPolicy.extendWindow_measurable
#print axioms Rectangular.KernelPolicy.execute_restrict
#print axioms Rectangular.KernelPolicy.completeCode_finite_law
#print axioms Rectangular.KernelPolicy.complete_encoding_injective
#print axioms Rectangular.KernelPolicy.execution_statistic_finite_law
#print axioms Rectangular.KernelPolicy.execution_risk_finite_eq

-- Revision 5: native randomized-decision compiler and oracle-uniform one-step law.
#print axioms Rectangular.KernelPolicy.code_standardBorel
#print axioms Rectangular.KernelPolicy.RawAction
#print axioms Rectangular.KernelPolicy.ValidAction
#print axioms Rectangular.KernelPolicy.validAction_measurable
#print axioms Rectangular.KernelPolicy.Action
#print axioms Rectangular.KernelPolicy.action_nonempty
#print axioms Rectangular.KernelPolicy.action_standardBorel
#print axioms Rectangular.KernelPolicy.decode
#print axioms Rectangular.KernelPolicy.decode_encode
#print axioms Rectangular.KernelPolicy.normalizedCode_measurable
#print axioms Rectangular.KernelPolicy.continueBatch
#print axioms Rectangular.KernelPolicy.stopAction
#print axioms Rectangular.KernelPolicy.queryAction
#print axioms Rectangular.KernelPolicy.queryAction_roundtrip
#print axioms Rectangular.KernelPolicy.Transcript
#print axioms Rectangular.KernelPolicy.RandomizedPolicy
#print axioms Rectangular.KernelPolicy.sample
#print axioms Rectangular.KernelPolicy.sample_measurable
#print axioms Rectangular.KernelPolicy.sample_law
#print axioms Rectangular.KernelPolicy.decisionAt
#print axioms Rectangular.KernelPolicy.decisionAt_measurable
#print axioms Rectangular.KernelPolicy.decisionAt_causal
#print axioms Rectangular.KernelPolicy.toPolicy
#print axioms Rectangular.KernelPolicy.toPolicy_stop
#print axioms Rectangular.KernelPolicy.toPolicy_output
#print axioms Rectangular.KernelPolicy.toPolicy_batch
#print axioms Rectangular.KernelPolicy.query
#print axioms Rectangular.KernelPolicy.query_measurable
#print axioms Rectangular.KernelPolicy.observation
#print axioms Rectangular.KernelPolicy.observation_measurable
#print axioms Rectangular.KernelPolicy.observation_stop
#print axioms Rectangular.KernelPolicy.observation_continue
#print axioms Rectangular.KernelPolicy.sample_observation_law
#print axioms Rectangular.KernelPolicy.internalTapeLaw
#print axioms Rectangular.KernelPolicy.internalTapeLaw_probability
#print axioms Rectangular.KernelPolicy.internalTapeLaw_restrict

-- Revision 4: kernel randomization and independent finite-tape execution.
#print axioms KernelRandomization.OpenUnit
#print axioms KernelRandomization.quantile
#print axioms KernelRandomization.quantile_set_nonempty
#print axioms KernelRandomization.quantile_set_bddBelow
#print axioms KernelRandomization.quantile_lt_iff
#print axioms KernelRandomization.quantile_le_iff
#print axioms KernelRandomization.quantile_lt_iff_rat
#print axioms KernelRandomization.quantile_measurable
#print axioms KernelRandomization.uniform
#print axioms KernelRandomization.uniform_probability
#print axioms KernelRandomization.toOpen
#print axioms KernelRandomization.toOpen_measurable
#print axioms KernelRandomization.realSampler
#print axioms KernelRandomization.realSampler_measurable
#print axioms KernelRandomization.uniform_Iic
#print axioms KernelRandomization.realSampler_map
#print axioms KernelRandomization.real_kernel_randomization
#print axioms KernelRandomization.standardBorel_kernel_randomization
#print axioms KernelRandomization.independent_seed_step
#print axioms KernelRandomization.SeedTape
#print axioms KernelRandomization.seedTapeMeasurableSpace
#print axioms KernelRandomization.seedTapeLaw
#print axioms KernelRandomization.seedTapeLaw_probability
#print axioms KernelRandomization.tapeRun
#print axioms KernelRandomization.tapeRun_measurable
#print axioms KernelRandomization.kernelRunLaw
#print axioms KernelRandomization.tapeRun_law
#print axioms KernelRandomization.finite_tape_representation

-- Revision 3: exact external boundary and its proved compatibility consequences.
#print axioms importedLemmaB1Certificate
#print axioms lemmaB1_paper
#print axioms importedLemma21Certificate
#print axioms PaperLemmaB1.origin_grad_bound
#print axioms PaperLemmaB1.toLegacy
#print axioms PaperLemmaB1.grad_lipschitz_slack
#print axioms GeneralLift.propositionF1_paper
#print axioms GeneralLift.propositionF1_calibrated_paper
#print axioms GeneralLift.paperChainBase
#print axioms GeneralLift.paperChainBase_gradient

-- Revision 2: exact progress and common-event probability interfaces.
#print axioms roundExpect_split
#print axioms roundExpect_increment_le
#print axioms roundExpect_total_progress_le
#print axioms progress_probability_exact
#print axioms lemma35_bernoulli_paper
#print axioms lemma35_bernoulli_support_paper
#print axioms progress_three_quarters_from_exact
#print axioms CommonEventPZC
#print axioms probabilityPZeroChain
#print axioms CommonEventPZC.same_seed_batch
#print axioms CommonEventPZC.simultaneous_no_skip
#print axioms commonEventPZC_of_bernoulli
#print axioms lemmaC1_bv_paper
#print axioms lemmaC1_as_paper
#print axioms roundProb_eq_measureReal
#print axioms lemma35_bernoulli_measure_paper

-- Current manuscript-facing additions; the existing audit below also checks legacy internals.
#print axioms theorem41_paper
#print axioms theorem51_paper
#print axioms corollary52_bv_paper
#print axioms corollary52_as_paper
#print axioms same_output_envelope_reverse
#print axioms lemmaF2_paper
#print axioms lemmaF2_calibrated_paper
#print axioms GeneralLift.proposition31_paper
#print axioms GeneralLift.proposition31_variance_paper
#print axioms GeneralLift.proposition31_AS_paper

#print axioms explicitFT_smooth_remainder_bounds
#print axioms explicitFT_smooth_upper
#print axioms explicitFT_smooth_lower
#print axioms canonicalProposition46
#print axioms canonicalProposition46Randomized
#print axioms canonicalScopeStatement
#print axioms canonicalScopeStatementV43

#print axioms populationFromLift_bddBelow
#print axioms canonicalGaussian_bddBelow
#print axioms canonicalLiftGradPhi_lipschitz
#print axioms canonicalLiftGradPhi_lipschitz_calibrated
#print axioms same_output_envelope_transfer
#print axioms envelope_hard_event_margin
#print axioms progress_probability_three_quarters
#print axioms manuscript_C2_moments
#print axioms bv_internal_random_risk_lower
#print axioms as_internal_random_risk_lower
#print axioms bv_internal_random_norm_lower
#print axioms as_internal_random_norm_lower
#print axioms ManuscriptCalibration.nu_eq
#print axioms ManuscriptCalibration.gamma_q
#print axioms ManuscriptCalibration.q_sq
#print axioms ManuscriptCalibration.stronglyConcave
#print axioms ManuscriptCalibration.primal_lipschitz
#print axioms ManuscriptCalibration.hard_event_moments
#print axioms pairGrowthRunProgress
#print axioms ManuscriptCalibration.in_class
#print axioms ManuscriptCalibration.bv_moments
#print axioms ManuscriptCalibration.as_moments
#print axioms ManuscriptBVProblem.in_class
#print axioms ManuscriptBVProblem.unbiased
#print axioms ManuscriptBVProblem.variance
#print axioms ManuscriptBVProblem.rate_threshold
#print axioms ManuscriptBVProblem.randomized_moments
#print axioms ManuscriptBVProblem.randomized_rate_lower
#print axioms ManuscriptBVProblem.fixed_instance_lower_bound
#print axioms universalS0_le_manuscriptS
#print axioms manuscriptAS_constants_pos
#print axioms manuscriptASRate_noise_free
#print axioms manuscriptASRate_le_bvRate
#print axioms manuscriptASProblem
#print axioms ManuscriptASProblem.scale_ge_sixteen
#print axioms ManuscriptASProblem.in_class
#print axioms ManuscriptASProblem.unbiased
#print axioms ManuscriptASProblem.variance
#print axioms ManuscriptASProblem.averaged_smooth
#print axioms ManuscriptASProblem.moments
#print axioms ManuscriptASProblem.chain_rate_threshold
#print axioms ManuscriptASProblem.mixed_factor_lower
#print axioms ManuscriptASProblem.rate_threshold
#print axioms ManuscriptASProblem.randomized_moments
#print axioms ManuscriptASProblem.fixed_instance_lower_bound
#print axioms ActualConditionNumberCertificate.optimal_bounds
#print axioms ActualConditionNumberCertificate.optimal_attained
#print axioms ActualConditionNumberCertificate.optimal_extremal
#print axioms ActualAveragedConditionNumberCertificate.optimal_attained
#print axioms ManuscriptCalibration.actualCertificate
#print axioms ManuscriptBVProblem.actual_constants
#print axioms ManuscriptBVProblem.actual_condition_number
#print axioms ManuscriptBVProblem.actual_constants_attained
#print axioms ManuscriptASProblem.actual_constants
#print axioms ManuscriptASProblem.actual_condition_numbers
#print axioms ManuscriptASProblem.actual_constants_attained
#print axioms ManuscriptBVProblem.fixed_instance_with_actual_condition
#print axioms ManuscriptASProblem.fixed_instance_with_actual_conditions

#print axioms CalibratedPrimal.existsUnique_minimizer
#print axioms CalibratedPrimal.envelope_eq_inf
#print axioms CalibratedPrimal.envelope_hasGradient
#print axioms CalibratedPrimal.same_output_transfer
#print axioms ManuscriptCalibration.primal
#print axioms ManuscriptCalibration.moreau_moments
#print axioms ManuscriptBVProblem.moreau_is_envelope
#print axioms ManuscriptBVProblem.moreau_hasGradient
#print axioms ManuscriptBVProblem.moreau_randomized_moments
#print axioms ManuscriptBVProblem.moreau_gradient_lower
#print axioms ManuscriptASProblem.moreau_is_envelope
#print axioms ManuscriptASProblem.moreau_hasGradient
#print axioms ManuscriptASProblem.moreau_randomized_moments
#print axioms ManuscriptASProblem.moreau_gradient_lower

#print axioms standardZeroRespecting_implies_pair
#print axioms StandardBernoulliRun.toPair
#print axioms StandardBernoulliRun.responses_eq_before
#print axioms StoppedStandardRun.inactive_response
#print axioms StoppedStandardRun.count_active_rounds
#print axioms StoppedStandardRun.unused_seeds_irrelevant
#print axioms BudgetStandardRun.stopImmediately
#print axioms ManuscriptBVProblem.standard_budget_lower
#print axioms ManuscriptBVProblem.standard_moreau_budget_lower
#print axioms ManuscriptASProblem.standard_budget_lower
#print axioms ManuscriptASProblem.standard_moreau_budget_lower
#print axioms worstCaseBudgetRisk_le_iff
#print axioms uniformBudgetComplexity_eq_top_of_no_success
#print axioms uniformBudgetComplexity_lower_of_fixed_instance
#print axioms ManuscriptBVProblem.uniform_complexity_lower
#print axioms ManuscriptBVProblem.uniform_moreau_complexity_lower
#print axioms ManuscriptASProblem.uniform_complexity_lower
#print axioms ManuscriptASProblem.uniform_moreau_complexity_lower

#print axioms OnlinePolicy.response_consistent
#print axioms OnlinePolicy.queries_causal
#print axioms OnlinePolicy.output_causal
#print axioms OnlinePolicy.stop_causal
#print axioms OnlinePolicy.active_batch
#print axioms OnlinePolicy.inactive_query
#print axioms OnlinePolicy.toBudgetRun
#print axioms OnlinePolicy.toBudgetRun_trace
#print axioms roundWeight_pos_of_non_degenerate
#print axioms OnlinePolicy.ae_legal_of_worldwise
#print axioms OnlinePolicy.normalize_legal
#print axioms onlineRisk_eq_normalized
#print axioms ManuscriptBVProblem.online_budget_lower
#print axioms ManuscriptBVProblem.online_moreau_budget_lower
#print axioms ManuscriptASProblem.online_budget_lower
#print axioms ManuscriptASProblem.online_moreau_budget_lower
#print axioms originUniformAlgorithm
#print axioms ManuscriptBVProblem.onlineInstance_valid
#print axioms ManuscriptBVProblem.online_moreau_gradient
#print axioms ManuscriptBVProblem.concrete_online_complexity_lower
#print axioms ManuscriptASProblem.onlineInstance_valid
#print axioms ManuscriptASProblem.online_moreau_gradient
#print axioms ManuscriptASProblem.concrete_online_complexity_lower

#print axioms relative_supported_prepend
#print axioms OnlinePolicy.repair_legal_relative
#print axioms OnlinePolicy.repair_preserves_legal_trace
#print axioms OnlinePolicy.repair_call_count_le
#print axioms OnlinePolicy.repairBudget_legal
#print axioms OnlinePolicy.repairBudget_preserves
#print axioms roundWeight_one_pos_iff
#print axioms AEOracleLegal_one_iff
#print axioms AEOracleLegal.eventually_all
#print axioms OnlinePolicy.repair_expectation_eq
#print axioms onlineRisk_eq_repair
#print axioms ManuscriptBVProblem.ae_online_budget_lower
#print axioms ManuscriptBVProblem.ae_online_moreau_budget_lower
#print axioms ManuscriptASProblem.ae_online_budget_lower
#print axioms ManuscriptASProblem.ae_online_moreau_budget_lower
#print axioms repairedUniformAlgorithm
#print axioms uniformOnlineRisk_repair_eq

#print axioms roundMeasure_probability
#print axioms lintegral_roundMeasure
#print axioms ofReal_roundExpect_eq_lintegral
#print axioms ae_roundMeasure_iff
#print axioms aeOracleLegal_iff_iterated
#print axioms aeOracleLegal_iff_product
#print axioms onlineRisk_eq_iterated
#print axioms onlineRisk_eq_product
#print axioms measurable_onlineLoss
#print axioms ProductLegal.toAEOracleLegal
#print axioms ManuscriptBVProblem.product_online_budget_lower
#print axioms ManuscriptBVProblem.product_online_moreau_budget_lower
#print axioms ManuscriptASProblem.product_online_budget_lower
#print axioms ManuscriptASProblem.product_online_moreau_budget_lower

#print axioms slotCoordinate_ne_zero
#print axioms standardZeroRespecting_iff_coordinates
#print axioms ObservableMeasurable.support_event
#print axioms ObservableMeasurable.call_count
#print axioms ObservableMeasurable.legal_event
#print axioms measurableSet_prod_of_finite_slices
#print axioms ObservableMeasurable.joint
#print axioms ObservableOnline.productLegal
#print axioms ObservableOnline.loss_measurable
#print axioms repair_execute_ae_eq
#print axioms repair_onlineLoss_ae_eq
#print axioms repair_onlineLoss_aemeasurable
#print axioms repair_product_risk_eq
#print axioms ObservableOnline.repaired_loss_aemeasurable
#print axioms CalibratedPrimal.g_continuous
#print axioms CalibratedPrimal.prox_continuous
#print axioms CalibratedPrimal.envelopeGrad_continuous
#print axioms ManuscriptBVProblem.observable_product_budget_lower
#print axioms ManuscriptBVProblem.observable_product_moreau_budget_lower
#print axioms ManuscriptASProblem.observable_product_budget_lower
#print axioms ManuscriptASProblem.observable_product_moreau_budget_lower

#print axioms batchCode_active
#print axioms batchCode_coordinate
#print axioms measurable_answer_code
#print axioms CodedTraceMeasurable.observable
#print axioms CodedTraceMeasurable.halt
#print axioms CodedTraceMeasurable.prepend
#print axioms CodedTraceMeasurable.ite
#print axioms StatefulPolicy.execute_succ
#print axioms StatefulPolicy.execution_measurable
#print axioms StatefulPolicy.observableOnline
#print axioms measurable_findGreatest
#print axioms measurable_prog
#print axioms chain_gradient_continuous
#print axioms measurable_bvBaseOracle
#print axioms measurable_asBaseOracle
#print axioms measurable_liftedOracle
#print axioms ManuscriptBVProblem.oracle_measurable
#print axioms ManuscriptASProblem.oracle_measurable
#print axioms ManuscriptBVProblem.stateful_product_budget_lower
#print axioms ManuscriptBVProblem.stateful_product_moreau_budget_lower
#print axioms ManuscriptASProblem.stateful_product_budget_lower
#print axioms ManuscriptASProblem.stateful_product_moreau_budget_lower

#print axioms appendHistory_seed
#print axioms appendHistory_clock
#print axioms appendHistory_latest
#print axioms appendHistory_past
#print axioms initialHistory_measurable
#print axioms appendHistory_measurable
#print axioms initialHistory_padded
#print axioms appendHistory_padded
#print axioms HistoryPolicy.toStateful
#print axioms HistoryPolicy.toStateful_toOnline
#print axioms HistoryPolicy.execute_eq
#print axioms HistoryPolicy.stop_eq
#print axioms HistoryPolicy.observableOnline
#print axioms HistoryPolicy.risk_eq
#print axioms ManuscriptBVProblem.history_product_budget_lower
#print axioms ManuscriptBVProblem.history_product_moreau_budget_lower
#print axioms ManuscriptASProblem.history_product_budget_lower
#print axioms ManuscriptASProblem.history_product_moreau_budget_lower

#print axioms restrictHistory_measurable
#print axioms appendFiniteHistory_measurable
#print axioms historyPrefix_append
#print axioms liftFiniteRule_measurable
#print axioms liftFiniteRule_prefix_invariant
#print axioms FiniteHistoryPolicy.toHistory
#print axioms FiniteHistoryPolicy.toHistory_toOnline
#print axioms FiniteHistoryPolicy.execute_eq
#print axioms FiniteHistoryPolicy.stop_eq
#print axioms FiniteHistoryPolicy.initial_prefix
#print axioms FiniteHistoryPolicy.observableOnline
#print axioms FiniteHistoryPolicy.risk_eq
#print axioms ManuscriptBVProblem.finite_history_product_budget_lower
#print axioms ManuscriptBVProblem.finite_history_product_moreau_budget_lower
#print axioms ManuscriptASProblem.finite_history_product_budget_lower
#print axioms ManuscriptASProblem.finite_history_product_moreau_budget_lower

#print axioms extendHistoryRule_measurable
#print axioms zeroDefaultBatch
#print axioms PartialHistoryPolicy.extend
#print axioms PartialHistoryPolicy.extend_stop
#print axioms PartialHistoryPolicy.extend_output
#print axioms PartialHistoryPolicy.extend_batch
#print axioms PartialHistoryPolicy.extend_execute_of_run
#print axioms PartialHistoryPolicy.extend_dummy_independent
#print axioms PartialHistoryPolicy.extend_halts_outside
#print axioms PartialHistoryPolicy.trace_eq_extend_ae
#print axioms PartialHistoryPolicy.loss_eq_extend_ae
#print axioms PartialHistoryPolicy.risk_eq_extend
#print axioms PartialHistoryPolicy.extend_legal
#print axioms PartialHistoryPolicy.loss_aemeasurable
#print axioms ManuscriptBVProblem.partial_history_product_budget_lower
#print axioms ManuscriptBVProblem.partial_history_product_moreau_budget_lower
#print axioms ManuscriptASProblem.partial_history_product_budget_lower
#print axioms ManuscriptASProblem.partial_history_product_moreau_budget_lower

#print axioms StoppingHistoryPolicy.stopped_measurable
#print axioms StoppingHistoryPolicy.continuing_measurable
#print axioms StoppingHistoryPolicy.toPartial
#print axioms StoppingHistoryPolicy.toPartial_output
#print axioms StoppingHistoryPolicy.toPartial_batch
#print axioms StoppingHistoryPolicy.run_zero_continuing
#print axioms StoppingHistoryPolicy.run_stopped
#print axioms StoppingHistoryPolicy.run_zero_defined_iff
#print axioms StoppingHistoryPolicy.toPartial_run_of_run
#print axioms StoppingHistoryPolicy.extend_execute_of_run
#print axioms StoppingHistoryPolicy.admissible_of_pathwise_budget
#print axioms StoppingHistoryPolicy.toPartial_admissible
#print axioms StoppingHistoryPolicy.trace_eq_toPartial_ae
#print axioms StoppingHistoryPolicy.loss_eq_toPartial_ae
#print axioms StoppingHistoryPolicy.risk_eq_toPartial
#print axioms StoppingHistoryPolicy.loss_aemeasurable
#print axioms ManuscriptBVProblem.stopping_history_product_budget_lower
#print axioms ManuscriptBVProblem.stopping_history_product_moreau_budget_lower
#print axioms ManuscriptASProblem.stopping_history_product_budget_lower
#print axioms ManuscriptASProblem.stopping_history_product_moreau_budget_lower

#print axioms StoppingHistoryPolicy.origin
#print axioms StoppingHistoryPolicy.origin_run
#print axioms StoppingHistoryPolicy.origin_trace
#print axioms RandomizedStoppingFamily.ofPolicies
#print axioms RandomizedStoppingFamily.admissible
#print axioms originStoppingBudgetAlgorithm
#print axioms uniformStoppingBudgetAlgorithm_nonempty
#print axioms uniformBudgetComplexity_le_of_restriction
#print axioms uniformStoppingComplexity_mono
#print axioms ManuscriptBVProblem.uniform_stopping_complexity_lower
#print axioms ManuscriptBVProblem.uniform_stopping_superclass_lower
#print axioms ManuscriptASProblem.uniform_stopping_complexity_lower
#print axioms ManuscriptASProblem.uniform_stopping_superclass_lower

#print axioms Rectangular.encode_square
#print axioms Rectangular.answer_square
#print axioms Rectangular.support_toSquare
#print axioms Rectangular.calls_toSquare
#print axioms Rectangular.Policy.toSquare
#print axioms Rectangular.Policy.run_toSquare
#print axioms Rectangular.Policy.trace_toSquare
#print axioms Rectangular.Policy.budget_toSquare
#print axioms Rectangular.Policy.risk_toSquare
#print axioms Rectangular.Instance.ofSquare
#print axioms Rectangular.Instance.ofSquare_validBV
#print axioms Rectangular.Instance.ofSquare_validAS
#print axioms Rectangular.Instance.field_ofSquare
#print axioms Rectangular.Family.diagonal
#print axioms Rectangular.Family.diagonal_legal
#print axioms Rectangular.Family.risk_diagonal
#print axioms Rectangular.Policy.origin
#print axioms Rectangular.Policy.origin_run
#print axioms Rectangular.originFamily
#print axioms Rectangular.originFamily_legal
#print axioms Rectangular.budgetAlgorithm_nonempty
#print axioms Rectangular.complexity_diagonal_le
#print axioms Rectangular.bv_complexity_lower
#print axioms Rectangular.as_complexity_lower

#print axioms bernoulliMeasure_finite
#print axioms bernoulliMeasure_probability
#print axioms bernoulliMeasure_singleton
#print axioms integral_bernoulliMeasure
#print axioms integral_bernoulliReal
#print axioms integral_bernoulliVec
#print axioms iidRoundMeasure_probability
#print axioms iidRoundMeasure_rectangle
#print axioms roundMeasure_singleton
#print axioms iidRoundMeasure_bernoulli
#print axioms MeasuredOracle.Instance.ofBernoulli
#print axioms MeasuredOracle.Instance.ofBernoulli_validBV
#print axioms MeasuredOracle.Instance.ofBernoulli_validAS
#print axioms MeasuredOracle.Instance.field_ofBernoulli
#print axioms MeasuredOracle.legal_restrict
#print axioms MeasuredOracle.risk_ofBernoulli
#print axioms MeasuredOracle.origin_legal
#print axioms MeasuredOracle.budgetAlgorithm_nonempty
#print axioms MeasuredOracle.complexity_bernoulli_le
#print axioms MeasuredOracle.bv_complexity_lower
#print axioms MeasuredOracle.as_complexity_lower

#print axioms Rectangular.jointlyMeasurable_bool_iff
#print axioms Rectangular.answerCode_encode
#print axioms Rectangular.answerCode_measurable
#print axioms Rectangular.append_measurable
#print axioms Rectangular.Policy.totalStop_measurable
#print axioms Rectangular.Policy.totalOutput_measurable
#print axioms Rectangular.Policy.totalQuery_measurable
#print axioms Rectangular.Policy.nextHistory_measurable
#print axioms Rectangular.Policy.summarize_prepend
#print axioms Rectangular.Policy.runSummary_eq_run
#print axioms Rectangular.Policy.runSummary_measurable
#print axioms Rectangular.Policy.summary_output
#print axioms Rectangular.Policy.summary_defined
#print axioms Rectangular.Policy.trace_output_measurable
#print axioms Rectangular.Policy.defined_measurable
#print axioms MeasuredOracle.loss_measurable
#print axioms MeasuredOracle.risk_eq_iterated
#print axioms CalibratedPrimal.g_measurable
#print axioms CalibratedPrimal.prox_measurable
#print axioms CalibratedPrimal.envelopeGrad_measurable
#print axioms ManuscriptBVProblem.measured_oracle_jointlyMeasurable
#print axioms ManuscriptASProblem.measured_oracle_jointlyMeasurable
#print axioms ManuscriptBVProblem.measured_field_measurable
#print axioms ManuscriptASProblem.measured_field_measurable
#print axioms ManuscriptBVProblem.measured_budget_lower
#print axioms ManuscriptASProblem.measured_budget_lower
#print axioms ManuscriptBVProblem.regular_measured_complexity_lower
#print axioms ManuscriptASProblem.regular_measured_complexity_lower

#print axioms Rectangular.encode_injective
#print axioms Rectangular.Trace.code_injective
#print axioms Rectangular.measurable_trace_iff_code
#print axioms Rectangular.partialCode_map
#print axioms Rectangular.haltCode_measurable
#print axioms Rectangular.prependCode_measurable
#print axioms Rectangular.Policy.runCode_eq_run
#print axioms Rectangular.Policy.runCode_measurable
#print axioms Rectangular.Policy.trace_code_measurable
#print axioms Rectangular.slotCoordinate_ne_zero
#print axioms Rectangular.standardSupport_iff_coordinates
#print axioms Rectangular.slotCoordinate_measurable
#print axioms Rectangular.active_measurable
#print axioms Rectangular.support_event_measurable
#print axioms Rectangular.calls_measurable
#print axioms Rectangular.Policy.trace_measurable
#print axioms Rectangular.Policy.trace_support_event
#print axioms Rectangular.Policy.trace_calls_measurable
#print axioms Rectangular.Policy.legalEvent_measurable
#print axioms Rectangular.Policy.legalEvent_iff_native
#print axioms Rectangular.Policy.ae_legalEvent_iff_iterated
#print axioms Rectangular.Policy.ae_support_iff_iterated
#print axioms MeasuredOracle.legal_iff_iterated

#print axioms Rectangular.Trace.Same.symm
#print axioms Rectangular.Trace.Same.trans
#print axioms Rectangular.queryAt_fin
#print axioms Rectangular.responseAt_fin
#print axioms Rectangular.queryAt_some_lt
#print axioms Rectangular.responseAt_some_lt
#print axioms Rectangular.standardSupport_iff_nat
#print axioms Rectangular.Trace.Same.support_iff
#print axioms Rectangular.haltTrace_same
#print axioms Rectangular.queryAt_prepend_zero
#print axioms Rectangular.queryAt_prepend_succ
#print axioms Rectangular.responseAt_prepend_zero
#print axioms Rectangular.responseAt_prepend_succ
#print axioms Rectangular.prepend_same
#print axioms Rectangular.calls_haltTrace
#print axioms Rectangular.calls_prepend
#print axioms Rectangular.Policy.runNat_budget_normalize
#print axioms Rectangular.Policy.runNat_budget_normalize_legal
#print axioms Rectangular.Policy.runNat_query_empty_after_calls
#print axioms Rectangular.Policy.runNat_response_empty_after_calls
#print axioms Rectangular.Policy.runNat_success_unique
#print axioms Rectangular.Policy.runNat_budget_prefix
#print axioms Rectangular.Policy.trace_same_of_runNat
#print axioms Rectangular.Policy.loss_eq_of_runNat
#print axioms Rectangular.Policy.eventuallyLegal_iff
#print axioms Rectangular.Policy.eventuallyLegal_measurable
#print axioms Rectangular.Policy.extendWorld_fin
#print axioms Rectangular.Policy.eventualBudget_iff_finite
#print axioms MeasuredOracle.Instance.seed_nonempty
#print axioms MeasuredOracle.eventualLegal_iff
#print axioms ManuscriptBVProblem.eventual_measured_budget_lower
#print axioms ManuscriptASProblem.eventual_measured_budget_lower

#print axioms Rectangular.sum_prefix_slots
#print axioms Rectangular.orderedBatch_size
#print axioms Rectangular.answer_orderedBatch
#print axioms Rectangular.orderedBatch_measurable
#print axioms Rectangular.OrderedQueries.code_measurable
#print axioms Rectangular.PositiveOrderedQueries.toNative_size
#print axioms Rectangular.PositiveOrderedQueries.toNative_measurable
#print axioms Rectangular.historyInit_measurable
#print axioms Rectangular.historyInit_append
#print axioms Rectangular.MemoryAlgorithm.replay_measurable
#print axioms Rectangular.MemoryAlgorithm.replay_append
#print axioms Rectangular.MemoryAlgorithm.replayDomain_measurable
#print axioms Rectangular.MemoryAlgorithm.toPolicy_run
#print axioms Rectangular.MemoryAlgorithm.toPolicy_initial_run
#print axioms Rectangular.MemoryAlgorithm.exists_history_representation
#print axioms Rectangular.MemoryAlgorithm.toPolicy_trace
#print axioms Rectangular.MemoryAlgorithm.toPolicy_loss
#print axioms Rectangular.MemoryAlgorithm.trace_measurable
#print axioms Rectangular.MemoryAlgorithm.loss_measurable
#print axioms Rectangular.MemoryAlgorithm.eventualBudget_iff_toPolicy
#print axioms Rectangular.MemoryAlgorithm.eventualBudget_iff_finite
#print axioms Rectangular.Policy.toMemory_run
#print axioms Rectangular.Policy.exists_memory_representation
#print axioms Rectangular.Policy.toMemory_trace
#print axioms Rectangular.Policy.toMemory_loss
#print axioms Rectangular.Policy.toMemory_replay
#print axioms Rectangular.Policy.toMemory_toPolicy_run
#print axioms Rectangular.MemoryAlgorithm.toPolicy_toMemory_initial_run
#print axioms MemoryModel.compile_legal_iff
#print axioms MemoryModel.compile_risk
#print axioms MemoryModel.ofHistory_legal_iff
#print axioms MemoryModel.ofHistory_risk
#print axioms MemoryModel.eventualLegal_iff
#print axioms MemoryModel.complexity_eq_history
#print axioms MemoryModel.bv_complexity_lower
#print axioms MemoryModel.as_complexity_lower

#print axioms WeaklyConvexPrimal.continuous_F
#print axioms WeaklyConvexPrimal.cost_continuous
#print axioms WeaklyConvexPrimal.exists_minimizer
#print axioms WeaklyConvexPrimal.prox_minimizes
#print axioms WeaklyConvexPrimal.cost_hasGradient
#print axioms WeaklyConvexPrimal.prox_first_order
#print axioms WeaklyConvexPrimal.envelopeGrad_eq
#print axioms WeaklyConvexPrimal.prox_quadratic_growth
#print axioms WeaklyConvexPrimal.prox_unique
#print axioms WeaklyConvexPrimal.existsUnique_minimizer
#print axioms WeaklyConvexPrimal.envelope_eq_inf
#print axioms WeaklyConvexPrimal.cost_increment
#print axioms WeaklyConvexPrimal.prox_cocoercive
#print axioms WeaklyConvexPrimal.prox_lipschitz
#print axioms WeaklyConvexPrimal.prox_continuous
#print axioms WeaklyConvexPrimal.envelopeGrad_continuous
#print axioms WeaklyConvexPrimal.envelopeGrad_lipschitz
#print axioms WeaklyConvexPrimal.envelope_remainder
#print axioms WeaklyConvexPrimal.envelope_hasGradient
#print axioms WeaklyConvexPrimal.infEnvelope_hasGradient
#print axioms WeaklyConvexPrimal.infEnvelope_gradient
#print axioms WeaklyConvexPrimal.infEnvelope_gradient_measurable
#print axioms measurable_gradient_vec
#print axioms MeasuredOracle.Instance.field_measurable
#print axioms MeasuredOracle.Instance.regularFor_iff_oracle
#print axioms gradient_lower_model
#print axioms Rectangular.Population.gradPhi_eq_at_max
#print axioms Rectangular.Population.lower_model_of_slice_lipschitz
#print axioms MeasuredOracle.Instance.PopulationValid.slice_lipschitz
#print axioms MeasuredOracle.Instance.moreau_existsUnique
#print axioms MeasuredOracle.Instance.moreau_hasGradient
#print axioms MeasuredOracle.Instance.moreau_field_eq
#print axioms MeasuredOracle.Instance.moreau_field_lipschitz
#print axioms MeasuredOracle.risk_eq_iterated_of_jointlyMeasurable
#print axioms MemoryModel.bv_complexity_lower_jointlyMeasurable
#print axioms MemoryModel.as_complexity_lower_jointlyMeasurable

#print axioms SmoothStronglyConcave.ofDifferentiable
#print axioms SmoothStronglyConcave.continuous_y
#print axioms SmoothStronglyConcave.exists_maximizer
#print axioms SmoothStronglyConcave.yStar_maximizes
#print axioms SmoothStronglyConcave.yStar_stationary
#print axioms SmoothStronglyConcave.yStar_quadratic_growth
#print axioms SmoothStronglyConcave.yStar_unique
#print axioms SmoothStronglyConcave.existsUnique_maximizer
#print axioms SmoothStronglyConcave.gradX_bound
#print axioms SmoothStronglyConcave.gradY_bound
#print axioms SmoothStronglyConcave.gradX_x_lipschitz
#print axioms SmoothStronglyConcave.gradX_y_lipschitz
#print axioms SmoothStronglyConcave.gradY_x_lipschitz
#print axioms SmoothStronglyConcave.gradY_strong_antimonotone
#print axioms SmoothStronglyConcave.yStar_lipschitz
#print axioms SmoothStronglyConcave.Phi_eq_sup
#print axioms SmoothStronglyConcave.slice_upper
#print axioms SmoothStronglyConcave.Phi_remainder_lower
#print axioms SmoothStronglyConcave.Phi_remainder_upper
#print axioms SmoothStronglyConcave.Phi_remainder
#print axioms SmoothStronglyConcave.Phi_hasGradient
#print axioms SmoothStronglyConcave.gradPhi_lipschitz
#print axioms SmoothStronglyConcave.yStar_continuous
#print axioms SmoothStronglyConcave.gradPhi_continuous
#print axioms SmoothStronglyConcave.population_Phi_eq_sup
#print axioms SmoothStronglyConcave.population_gradPhi_eq
#print axioms SmoothStronglyConcave.minimax_moreau_hasGradient
#print axioms Rectangular.Population.ext_of_primitives
#print axioms MeasuredOracle.Instance.primitive_population
#print axioms MeasuredOracle.Instance.ofPrimitive_populationValid
#print axioms MeasuredOracle.Instance.ofPrimitive_primitive
#print axioms MeasuredOracle.Instance.populationValid_iff_primitive
#print axioms MeasuredOracle.Instance.ofPrimitive_validBV_iff
#print axioms MeasuredOracle.Instance.ofPrimitive_validAS_iff
#print axioms MeasuredOracle.Instance.validBV_iff_primitive
#print axioms MeasuredOracle.Instance.validAS_iff_primitive
#print axioms MemoryModel.risk_primitive_reconstruction

/-! Revision 25: general lift/Hessian, joint C1 class, and literal gate constant. -/
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.inner_initialization_gap
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.simulateResponse
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.single_query_simulation
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.same_seed_batch_simulation
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.same_seed_batch_law
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.quadraticField_continuous
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_jointlyMeasurable
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.proposition31_oracle
#print axioms NCSCPureStochasticLB.PaperExact.gammaGate_hasDerivAt
#print axioms NCSCPureStochasticLB.PaperExact.gammaGate_deriv
#print axioms NCSCPureStochasticLB.PaperExact.lambdaGate_le_peak
#print axioms NCSCPureStochasticLB.PaperExact.lambdaGate_peak
#print axioms NCSCPureStochasticLB.PaperExact.paperMGamma
#print axioms NCSCPureStochasticLB.PaperExact.paperMGamma_eq
#print axioms NCSCPureStochasticLB.PaperExact.paperMGamma_pos
#print axioms NCSCPureStochasticLB.PaperExact.paperMGamma_le_explicit
#print axioms NCSCPureStochasticLB.PaperExact.gammaGate_lipschitz_paper
#print axioms NCSCPureStochasticLB.PaperExact.paperSmoothGateCertificate
#print axioms NCSCPureStochasticLB.PaperExact.jointPoint
#print axioms NCSCPureStochasticLB.PaperExact.gradient_remainder_bound
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.jointFunction
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.jointGradient
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.jointGradient_lipschitz
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.joint_remainder
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.joint_hasGradient
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.joint_gradient
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.joint_contDiff
#print axioms NCSCPureStochasticLB.PaperExact.jointInl
#print axioms NCSCPureStochasticLB.PaperExact.jointInr
#print axioms NCSCPureStochasticLB.PaperExact.joint_partialX
#print axioms NCSCPureStochasticLB.PaperExact.joint_partialY
#print axioms NCSCPureStochasticLB.PaperExact.JointPrimitive
#print axioms NCSCPureStochasticLB.PaperExact.ofJointPrimitive
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.jointPrimitive
#print axioms NCSCPureStochasticLB.PaperExact.jointPrimitive_iff
#print axioms NCSCPureStochasticLB.PaperExact.jointPrimal
#print axioms NCSCPureStochasticLB.PaperExact.JointFunctionClass
#print axioms NCSCPureStochasticLB.PaperExact.SmoothStronglyConcave.jointPrimal_eq
#print axioms NCSCPureStochasticLB.PaperExact.jointFunctionClass_iff
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftParameters.α
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftParameters.β
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftParameters.ν
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftParameters.alpha_mul_beta
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftParameters.q_mul_beta
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_nu_pos
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedF
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.LiftStrongConcavity
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.explicitFT_smooth_upper
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_alpha_mul_beta_sq
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_quadratic_norm_expansion
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_chain_smooth_upper_scaled
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedF_mu_strong_concavity
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_quadratic_pair_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lift_chain_pair_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedF_joint_smoothness
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedF_gradX_formula
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedF_gradY_formula
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primitive
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftYStar
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftPhi
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftGradPhi
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftPhi_grad
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftPhi_eq_sup
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftYStar_dual_stationary
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftYStar_scaled_fixed_point
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftStrongConcavity_antimonotone
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftYStar_lipschitz
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftGradPhi_eq_scaled_chain
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLift_chain_gradient_comparison
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLift_stationarity_transfer_candidate
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftGradPhi_lipschitz
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.canonicalLiftGradPhi_lipschitz_calibrated
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.stationarity_transfer
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_lower_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_bddBelow
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_origin_upper
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_gap
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.Base.ofC2
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.proposition31
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.baseHessian
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.baseHessian_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolvent
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolvent_lower
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolvent_ker
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolventEquiv
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolventInv
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolvent_inv_left
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolvent_inv_right
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolventInv_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.normalizedResolventEquiv
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.inverseStationarity
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.inverseStationarity_yStar
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.inverseStationarity_hasFDeriv
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.yStar_hasFDeriv
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_hessian_formula
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.base_gradient_differentiable_of_C2
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.primal_hessian_formula_of_C2
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.baseHessian_eq_actual
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.resolventInv_opNorm
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.propositionF1
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.mean_norm_le_of_second_moment
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.second_moment_add_const
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_error
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_error_norm_sq
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.lifted_variance
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.quadraticField
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_decomposition
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_memLp
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_unbiased
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.quadraticField_bound
#print axioms NCSCPureStochasticLB.PaperExact.GeneralLift.liftedField_averaged_smooth

-- Revision 10: private stochastic memory and observation-dependent updates.
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.Model
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.initialSample
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.initialSample_measurable
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.initialSample_law
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.decisionSample
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.decisionSample_measurable
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.decisionSample_law
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.updateSample
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.updateSample_measurable
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.updateSample_law
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.RandomTape
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.randomTapeLaw
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.randomTapeLaw_probability
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.actionAt
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.actionAt_measurable
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.toMemory
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.toMemory_initial
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.toMemory_advance
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.toPolicy_run
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.update_independent_law
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.decision_independent_law
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.roundInput
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.roundInput_measurable
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.roundLaw
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.roundSample
#print axioms NCSCPureStochasticLB.PaperExact.Rectangular.StochasticMemory.roundSample_law
