import ManuscriptJointMeasurability

noncomputable section
open MeasureTheory
open scoped ENNReal
namespace NCSCPureStochasticLB.PaperExact
namespace Rectangular

abbrev TraceCode (dx dy H K : ℕ) :=
  (Fin H → Code dx dy K) × (Fin H → Code dx dy K) × Vec dx

def Trace.code {dx dy H K : ℕ} (tr : Trace dx dy H K) : TraceCode dx dy H K :=
  (fun t => encode (tr.query t), fun t => encode (tr.response t), tr.output)

theorem encode_injective {dx dy K : ℕ} : Function.Injective (@encode dx dy K) := by
  intro q r h
  funext k
  have hk := congrFun h k
  cases hq : q k <;> cases hr : r k <;> simp [encode, hq, hr] at hk ⊢
  exact hk

theorem Trace.code_injective {dx dy H K : ℕ} : Function.Injective (@Trace.code dx dy H K) := by
  intro a b h
  have hq : a.query = b.query := funext (fun t => encode_injective (congrFun (congrArg Prod.fst h) t))
  have hr : a.response = b.response :=
    funext (fun t => encode_injective (congrFun (congrArg (fun z => z.2.1) h) t))
  have ho : a.output = b.output := congrArg (fun z => z.2.2) h
  cases a
  cases b
  simp_all

/-- The sigma-algebra generated by active flags and all finite real coordinates. -/
instance Trace.measurableSpace {dx dy H K : ℕ} : MeasurableSpace (Trace dx dy H K) :=
  MeasurableSpace.comap Trace.code inferInstance

theorem measurable_trace_iff_code {X : Type*} [MeasurableSpace X] {dx dy H K : ℕ}
    (f : X → Trace dx dy H K) : Measurable f ↔ Measurable (fun x => (f x).code) := by
  constructor
  · intro h
    exact (comap_measurable Trace.code).comp h
  · intro h s hs
    obtain ⟨t, ht, rfl⟩ := hs
    exact h ht

def haltCode {dx : ℕ} (x : Vec dx) (dy H K : ℕ) : TraceCode dx dy H K :=
  (fun _ _ => (false, 0, 0), fun _ _ => (false, 0, 0), x)

def prependCode {dx dy H K : ℕ} (q r : Code dx dy K) (tr : TraceCode dx dy H K) :
    TraceCode dx dy (H + 1) K := (Fin.cases q tr.1, Fin.cases r tr.2.1, tr.2.2)

def partialCode {dx dy H K : ℕ} (tr : Option (Trace dx dy H K)) : TraceCode dx dy H K :=
  (tr.getD (haltTrace 0 dy H K)).code

theorem partialCode_map {dx dy H K : ℕ} (q r : Batch dx dy K)
    (tr : Option (Trace dx dy H K)) :
    partialCode (tr.map (prepend q r)) =
      if tr.isSome = true then prependCode (encode q) (encode r) (partialCode tr)
      else haltCode 0 dy (H + 1) K := by
  cases tr with
  | none => rfl
  | some tr =>
    change (fun t => encode (Fin.cases q tr.query t),
      (fun t => encode (Fin.cases r tr.response t)), tr.output) =
      (Fin.cases (encode q) (fun t => encode (tr.query t)),
        Fin.cases (encode r) (fun t => encode (tr.response t)), tr.output)
    apply Prod.ext
    · funext t
      refine Fin.cases ?_ (fun j => ?_) t <;> rfl
    · apply Prod.ext
      · funext t
        refine Fin.cases ?_ (fun j => ?_) t <;> rfl
      · rfl

theorem haltCode_measurable {X : Type*} [MeasurableSpace X] {dx : ℕ}
    (x : X → Vec dx) (hx : Measurable x) (dy H K : ℕ) :
    Measurable (fun z => haltCode (x z) dy H K) :=
  measurable_const.prodMk (measurable_const.prodMk hx)

theorem prependCode_measurable {X : Type*} [MeasurableSpace X] {dx dy H K : ℕ}
    (q r : X → Code dx dy K) (tr : X → TraceCode dx dy H K)
    (hq : Measurable q) (hr : Measurable r) (ht : Measurable tr) :
    Measurable (fun z => prependCode (q z) (r z) (tr z)) := by
  apply Measurable.prodMk
  · apply measurable_pi_lambda
    intro t
    refine Fin.cases ?_ (fun j => ?_) t
    · exact hq
    · exact (measurable_pi_apply j).comp ht.fst
  · apply Measurable.prodMk
    · apply measurable_pi_lambda
      intro t
      refine Fin.cases ?_ (fun j => ?_) t
      · exact hr
      · exact (measurable_pi_apply j).comp ht.snd.fst
    · exact ht.snd.snd

namespace Policy
universe u
variable {Ω : Type u} [MeasurableSpace Ω] {dx dy K : ℕ}

/-- A full code of the native partial execution, with the same failure fallback. -/
def runCode {Seed : Type} (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) :
    (H n : ℕ) → History Ω dx dy K n → (Fin H → Seed) → TraceCode dx dy H K
  | 0, n, s, _ => by
    classical
    exact if s ∈ P.domain n then
      if P.totalStop n s = true then haltCode (P.totalOutput n s) dy 0 K else haltCode 0 dy 0 K
    else haltCode 0 dy 0 K
  | H + 1, n, s, w => by
    classical
    exact if s ∈ P.domain n then
      if P.totalStop n s = true then haltCode (P.totalOutput n s) dy (H + 1) K
      else
        let s' := P.nextHistory O n s (w 0)
        let w' := fun t : Fin H => w t.succ
        if (P.runSummary O H (n + 1) s' w').1 = true then
          prependCode (P.totalQuery n s) (answerCode O (P.totalQuery n s) (w 0))
            (P.runCode O H (n + 1) s' w')
        else haltCode 0 dy (H + 1) K
    else haltCode 0 dy (H + 1) K

theorem runCode_eq_run {Seed : Type} (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) :
    ∀ H n (s : History Ω dx dy K n) (w : Fin H → Seed),
      P.runCode O H n s w = partialCode (P.run? O H n s w) := by
  classical
  intro H
  induction H with
  | zero =>
    intro n s w
    by_cases hd : s ∈ P.domain n
    · by_cases hs : P.stop n ⟨s, hd⟩ = true <;>
        simp [runCode, run?, totalStop, totalOutput, extendHistoryRule, hd, hs,
          partialCode, Trace.code, haltTrace, haltCode, encode] <;> rfl
    · simp [runCode, run?, hd, partialCode, Trace.code, haltTrace, haltCode, encode]
      rfl
  | succ H ih =>
    intro n s w
    by_cases hd : s ∈ P.domain n
    · by_cases hs : P.stop n ⟨s, hd⟩ = true
      · simp [runCode, run?, totalStop, totalOutput, extendHistoryRule, hd, hs,
          partialCode, Trace.code, haltTrace, haltCode, encode]
        rfl
      · simp [runCode, run?, totalStop, totalOutput, totalQuery, nextHistory,
          extendHistoryRule, hd, hs, answerCode_encode, partialCode_map, ih, summary_defined]
    · simp [runCode, run?, hd, partialCode, Trace.code, haltTrace, haltCode, encode]
      rfl

theorem runCode_measurable {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) :
    ∀ H n, Measurable (fun z : History Ω dx dy K n × (Fin H → Seed) =>
      P.runCode O H n z.1 z.2) := by
  classical
  intro H
  induction H with
  | zero =>
    intro n
    exact Measurable.ite ((P.domain_measurable n).preimage measurable_fst)
      (Measurable.ite (measurableSet_eq_fun ((P.totalStop_measurable n).comp measurable_fst) measurable_const)
        (haltCode_measurable _ ((P.totalOutput_measurable n).comp measurable_fst) _ _ _) measurable_const)
      measurable_const
  | succ H ih =>
    intro n
    let step := fun z : History Ω dx dy K n × (Fin (H + 1) → Seed) =>
      (P.nextHistory O n z.1 (z.2 0), fun t : Fin H => z.2 t.succ)
    have hstep : Measurable step :=
      ((P.nextHistory_measurable O hO n).comp
        (measurable_fst.prodMk ((measurable_pi_apply 0).comp measurable_snd))).prodMk
        (measurable_pi_lambda _ (fun t => (measurable_pi_apply t.succ).comp measurable_snd))
    apply Measurable.ite ((P.domain_measurable n).preimage measurable_fst) _ measurable_const
    apply Measurable.ite
      (measurableSet_eq_fun ((P.totalStop_measurable n).comp measurable_fst) measurable_const)
      (haltCode_measurable _ ((P.totalOutput_measurable n).comp measurable_fst) _ _ _)
    apply Measurable.ite
      (measurableSet_eq_fun ((P.runSummary_measurable O hO H (n + 1)).comp hstep).fst measurable_const)
      _ measurable_const
    exact prependCode_measurable _ _ _ ((P.totalQuery_measurable n).comp measurable_fst)
      (answerCode_measurable O hO _ ((P.totalQuery_measurable n).comp measurable_fst)
        _ ((measurable_pi_apply 0).comp measurable_snd)) ((ih (n + 1)).comp hstep)

theorem trace_code_measurable {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) (N : ℕ) :
    Measurable (fun z : Ω × (Fin N → Seed) => (MeasuredOracle.trace P O N z).code) := by
  have hi : Measurable (fun z : Ω × (Fin N → Seed) =>
      (((z.1, Fin.elim0) : History Ω dx dy K 0), z.2)) :=
    (measurable_fst.prodMk measurable_const).prodMk measurable_snd
  have hm := (P.runCode_measurable O hO N 0).comp hi
  simpa only [Function.comp_def, runCode_eq_run, partialCode, MeasuredOracle.trace] using hm

end Policy

/-- A zero-padded coordinate of a native rectangular query/response slot. -/
def slotCoordinate {dx dy : ℕ} (q : Option (Pair dx dy)) (c : Fin dx ⊕ Fin dy) : ℝ :=
  match q with
  | none => 0
  | some z => Sum.elim z.1 z.2 c

theorem slotCoordinate_ne_zero {dx dy : ℕ} (q : Option (Pair dx dy)) (c : Fin dx ⊕ Fin dy) :
    slotCoordinate q c ≠ 0 ↔ ∃ z, q = some z ∧ c ∈ support z := by
  cases q <;> simp [slotCoordinate, support]

theorem standardSupport_iff_coordinates {dx dy H K : ℕ} (tr : Trace dx dy H K) :
    StandardSupport tr ↔
      (∀ t k c, slotCoordinate (tr.query t k) c ≠ 0 →
        ∃ s : Fin H, s.val < t.val ∧ ∃ j, slotCoordinate (tr.response s j) c ≠ 0) ∧
      (∀ c, Sum.elim tr.output (0 : Vec dy) c ≠ 0 →
        ∃ s j, slotCoordinate (tr.response s j) c ≠ 0) := by
  simp only [slotCoordinate_ne_zero]
  constructor
  · intro h
    constructor
    · intro t k c hc
      obtain ⟨q, hq, hc⟩ := hc
      obtain ⟨s, hs, j, r, hr, hc⟩ := h.1 t k q hq c hc
      exact ⟨s, hs, j, r, hr, hc⟩
    · intro c hc
      exact h.2 c hc
  · rintro ⟨hq, ho⟩
    constructor
    · intro t k q he c hc
      exact hq t k c ⟨q, he, hc⟩
    · intro c hc
      exact ho c hc

theorem slotCoordinate_measurable {X : Type*} [MeasurableSpace X] {dx dy K : ℕ}
    (q : X → Batch dx dy K) (hq : Measurable (fun x => encode (q x)))
    (k : Fin K) (c : Fin dx ⊕ Fin dy) :
    Measurable (fun x => slotCoordinate (q x k) c) := by
  have hk := (measurable_pi_apply k).comp hq
  have he (x : X) : slotCoordinate (q x k) c =
      Sum.elim (encode (q x) k).2.1 (encode (q x) k).2.2 c := by
    cases h : q x k <;> cases c <;> simp [slotCoordinate, encode, h]
  simp_rw [he]
  cases c with
  | inl i => exact (measurable_pi_apply i).comp hk.snd.fst
  | inr i => exact (measurable_pi_apply i).comp hk.snd.snd

theorem active_measurable {X : Type*} [MeasurableSpace X] {dx dy K : ℕ}
    (q : X → Batch dx dy K) (hq : Measurable (fun x => encode (q x))) (k : Fin K) :
    Measurable (fun x => (q x k).isSome) := by
  have he (x : X) : (q x k).isSome = (encode (q x) k).1 := by
    cases h : q x k <;> simp [encode, h]
  simp_rw [he]
  exact ((measurable_pi_apply k).comp hq).fst

theorem support_event_measurable {X : Type*} [MeasurableSpace X] {dx dy H K : ℕ}
    (tr : X → Trace dx dy H K) (ht : Measurable (fun x => (tr x).code)) :
    MeasurableSet {x | StandardSupport (tr x)} := by
  have hq := fun t => (measurable_pi_apply t).comp ht.fst
  have hr := fun t => (measurable_pi_apply t).comp ht.snd.fst
  simp only [standardSupport_iff_coordinates, imp_iff_not_or, not_not,
    Set.setOf_forall, Set.setOf_exists, Set.setOf_and, Set.setOf_or]
  apply MeasurableSet.inter
  · apply MeasurableSet.iInter
    intro t
    apply MeasurableSet.iInter
    intro k
    apply MeasurableSet.iInter
    intro c
    exact (measurableSet_eq_fun (slotCoordinate_measurable _ (hq t) k c) measurable_const).union
      (MeasurableSet.iUnion (fun s => (MeasurableSet.const _).inter
        (MeasurableSet.iUnion (fun j =>
          (measurableSet_eq_fun (slotCoordinate_measurable _ (hr s) j c) measurable_const).compl))))
  · apply MeasurableSet.iInter
    intro c
    have ho : Measurable (fun x => Sum.elim (tr x).output (0 : Vec dy) c) := by
      cases c with
      | inl i => exact (measurable_pi_apply i).comp ht.snd.snd
      | inr i => exact measurable_const
    exact (measurableSet_eq_fun ho measurable_const).union
      (MeasurableSet.iUnion (fun s => MeasurableSet.iUnion (fun j =>
        (measurableSet_eq_fun (slotCoordinate_measurable _ (hr s) j c) measurable_const).compl)))

theorem calls_measurable {X : Type*} [MeasurableSpace X] {dx dy H K : ℕ}
    (tr : X → Trace dx dy H K) (ht : Measurable (fun x => (tr x).code)) :
    Measurable (fun x => calls (tr x)) := by
  unfold calls batchSize
  apply Finset.measurable_sum
  intro t ht'
  apply Finset.measurable_sum
  intro k hk
  exact Measurable.ite
    (measurableSet_eq_fun (active_measurable _ ((measurable_pi_apply t).comp ht.fst) k)
      measurable_const) measurable_const measurable_const

namespace Policy
universe u
variable {Ω : Type u} [MeasurableSpace Ω] {dx dy K : ℕ}

theorem trace_measurable {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) (N : ℕ) :
    Measurable (MeasuredOracle.trace P O N) :=
  (measurable_trace_iff_code _).mpr (P.trace_code_measurable O hO N)

theorem trace_support_event {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) (N : ℕ) :
    MeasurableSet {z : Ω × (Fin N → Seed) | StandardSupport (MeasuredOracle.trace P O N z)} :=
  support_event_measurable _ (P.trace_code_measurable O hO N)

theorem trace_calls_measurable {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) (N : ℕ) :
    Measurable (fun z : Ω × (Fin N → Seed) => calls (MeasuredOracle.trace P O N z)) :=
  calls_measurable _ (P.trace_code_measurable O hO N)

/-- Successful genuine termination, standard support, and an actual call bound. -/
def LegalEvent {Seed : Type} (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (N B : ℕ)
    (z : Ω × (Fin N → Seed)) : Prop :=
  (P.run? O N 0 (z.1, Fin.elim0) z.2).isSome = true ∧
    StandardSupport (MeasuredOracle.trace P O N z) ∧ calls (MeasuredOracle.trace P O N z) ≤ B

theorem legalEvent_measurable {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O) (N B : ℕ) :
    MeasurableSet {z | P.LegalEvent O N B z} :=
  (measurableSet_eq_fun (P.defined_measurable O hO N) measurable_const).inter
    ((P.trace_support_event O hO N).inter
      (measurableSet_le (P.trace_calls_measurable O hO N) measurable_const))

theorem legalEvent_iff_native {Seed : Type} (P : Policy Ω dx dy K)
    (O : Oracle dx dy Seed) (N B : ℕ) (z : Ω × (Fin N → Seed)) :
    P.LegalEvent O N B z ↔ ∃ tr,
      P.run? O N 0 (z.1, Fin.elim0) z.2 = some tr ∧ StandardSupport tr ∧ calls tr ≤ B := by
  cases hr : P.run? O N 0 (z.1, Fin.elim0) z.2 <;>
    simp [LegalEvent, MeasuredOracle.trace, hr]

theorem ae_legalEvent_iff_iterated {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O)
    (ρ : Measure Ω) (ν : Measure Seed) [IsProbabilityMeasure ν] (N B : ℕ) :
    (∀ᵐ z ∂ρ.prod (iidRoundMeasure ν N), P.LegalEvent O N B z) ↔
      ∀ᵐ ω ∂ρ, ∀ᵐ w ∂iidRoundMeasure ν N, P.LegalEvent O N B (ω, w) := by
  letI := iidRoundMeasure_probability ν N
  exact Measure.ae_prod_iff_ae_ae (P.legalEvent_measurable O hO N B)

theorem ae_support_iff_iterated {Seed : Type} [MeasurableSpace Seed]
    (P : Policy Ω dx dy K) (O : Oracle dx dy Seed) (hO : JointlyMeasurable O)
    (ρ : Measure Ω) (ν : Measure Seed) [IsProbabilityMeasure ν] (N : ℕ) :
    (∀ᵐ z ∂ρ.prod (iidRoundMeasure ν N), StandardSupport (MeasuredOracle.trace P O N z)) ↔
      ∀ᵐ ω ∂ρ, ∀ᵐ w ∂iidRoundMeasure ν N, StandardSupport (MeasuredOracle.trace P O N (ω, w)) := by
  letI := iidRoundMeasure_probability ν N
  exact Measure.ae_prod_iff_ae_ae (P.trace_support_event O hO N)

end Policy
end Rectangular

namespace MeasuredOracle
universe u

/-- The existing legal algorithm class admits the iterated a.e. formulation,
without any extra hypothesis that its support event is measurable. -/
theorem legal_iff_iterated {K N : ℕ} (A : Rectangular.Family.{u} K)
    (valid : Instance → Prop) (hreg : ∀ I, valid I → Rectangular.JointlyMeasurable I.oracle) :
    Legal A valid N ↔ ∀ I, valid I →
      (∀ z : A.Seed I.dx I.dy × (Fin N → I.Seed), ∃ tr,
        (A.policy I.dx I.dy).run? I.oracle N 0 (z.1, Fin.elim0) z.2 = some tr ∧
          Rectangular.calls tr ≤ N) ∧
      ∀ᵐ ω ∂A.law I.dx I.dy, ∀ᵐ w ∂iidRoundMeasure I.law N,
        Rectangular.StandardSupport (trace (A.policy I.dx I.dy) I.oracle N (ω, w)) := by
  unfold Legal
  apply forall_congr'
  intro I
  apply forall_congr'
  intro hI
  exact and_congr_right (fun _ =>
    (A.policy I.dx I.dy).ae_support_iff_iterated I.oracle (hreg I hI) (A.law I.dx I.dy) I.law N)

end MeasuredOracle
end NCSCPureStochasticLB.PaperExact
